Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "lvm-lab"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1

  end

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
   config.vm.network "public_network"

  # Add a second virtual disk for LVM practice
  config.vm.disk :disk, size: "5GB", name: "lvm-disk", primary: false

  config.vm.provision "shell", inline: <<-SHELL
    yum -y install lvm2
  SHELL
end

